spring.application.name=service-reporte
server.port=8091

spring.datasource.url=jdbc:mysql://localhost:3306/db_reporte?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/api/v1/reportes/v3/api-docs

# Título de la documentación
springdoc.swagger-ui.path=/swagger-ui.html